var fakeData = [
    { ID: 1, Name: 'Brand', Members: 120, Folders: 300, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 2, Name: 'Compliance', Members: 14, Folders: 3, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 3, Name: 'Corporate', Members: 7, Folders: 10, Quota: null, PolicySet: 'Default' },
    { ID: 4, Name: 'Education', Members: 21, Folders: 11, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 5, Name: 'Finance', Members: 12, Folders: 1, Quota: null, PolicySet: 'Default' },
    { ID: 6, Name: 'Sales QQQ', Members: 9, Folders: 0, Quota: null, PolicySet: 'Default' },
    { ID: 7, Name: 'Sales PPP', Members: 33, Folders: 14, Quota: null, PolicySet: 'Default' },
    { ID: 8, Name: 'Sales AAA', Members: 89, Folders: 6, Quota: null, PolicySet: 'Laissez Faire' },
    { ID: 9, Name: 'Sales YYY', Members: 120, Folders: 300, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 10, Name: 'Sales TTT', Members: 14, Folders: 200, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 11, Name: 'Sales GGG', Members: 7, Folders: 3, Quota: null, PolicySet: 'Default' },
    { ID: 12, Name: 'Sales BBB', Members: 21, Folders: 11, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 13, Name: 'Sales CCC', Members: 12, Folders: 4, Quota: null, PolicySet: 'Default' },
    { ID: 14, Name: 'Sales DDD', Members: 9, Folders: 5, Quota: null, PolicySet: 'Default' },
    { ID: 15, Name: 'Sales OOO', Members: 33, Folders: 6, Quota: null, PolicySet: 'Default' },
    { ID: 16, Name: 'Sales NNN', Members: 89, Folders: 12, Quota: null, PolicySet: 'Laissez Faire' },
    { ID: 17, Name: 'Sales MMM', Members: 120, Folders: 20, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 18, Name: 'Sales LLL', Members: 120, Folders: 111, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 19, Name: 'Sales KKK', Members: 7, Folders: 45, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 20, Name: 'Sales JJJ', Members: 10, Folders: 0, Quota: null, PolicySet: 'Default' },
    { ID: 21, Name: 'Sales III', Members: 14, Folders: 4, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 22, Name: 'Sales HHH', Members: 9, Folders: 2, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 23, Name: 'Sales GGG', Members: 33, Folders: 1, Quota: null, PolicySet: 'Default' },
    { ID: 24, Name: 'Sales FFF', Members: 22, Folders: 44, Quota: null, PolicySet: 'Default' },
    { ID: 25, Name: 'Sales EEE', Members: 2, Folders: 4, Quota: null, PolicySet: 'Laissez Faire' },
    { ID: 26, Name: 'Brand', Members: 120, Folders: 300, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 27, Name: 'Compliance', Members: 14, Folders: 3, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 28, Name: 'Corporate', Members: 7, Folders: 10, Quota: null, PolicySet: 'Default' },
    { ID: 29, Name: 'Education', Members: 21, Folders: 11, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 30, Name: 'Finance', Members: 12, Folders: 1, Quota: null, PolicySet: 'Default' },
    { ID: 31, Name: 'Sales QQQ', Members: 9, Folders: 0, Quota: null, PolicySet: 'Default' },
    { ID: 32, Name: 'Sales PPP', Members: 33, Folders: 14, Quota: null, PolicySet: 'Default' },
    { ID: 33, Name: 'Sales AAA', Members: 89, Folders: 6, Quota: null, PolicySet: 'Laissez Faire' },
    { ID: 34, Name: 'Sales YYY', Members: 120, Folders: 300, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 35, Name: 'Sales TTT', Members: 14, Folders: 200, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 36, Name: 'Sales GGG', Members: 7, Folders: 3, Quota: null, PolicySet: 'Default' },
    { ID: 37, Name: 'Sales BBB', Members: 21, Folders: 11, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 38, Name: 'Sales CCC', Members: 12, Folders: 4, Quota: null, PolicySet: 'Default' },
    { ID: 39, Name: 'Sales DDD', Members: 9, Folders: 5, Quota: null, PolicySet: 'Default' },
    { ID: 40, Name: 'Sales OOO', Members: 33, Folders: 6, Quota: null, PolicySet: 'Default' },
    { ID: 41, Name: 'Sales NNN', Members: 89, Folders: 12, Quota: null, PolicySet: 'Laissez Faire' },
    { ID: 42, Name: 'Sales MMM', Members: 120, Folders: 20, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 43, Name: 'Sales LLL', Members: 120, Folders: 111, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 44, Name: 'Sales KKK', Members: 7, Folders: 45, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 45, Name: 'Sales JJJ', Members: 10, Folders: 0, Quota: null, PolicySet: 'Default' },
    { ID: 46, Name: 'Sales III', Members: 14, Folders: 4, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 47, Name: 'Sales HHH', Members: 9, Folders: 2, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 48, Name: 'Sales GGG', Members: 33, Folders: 1, Quota: null, PolicySet: 'Default' },
    { ID: 49, Name: 'Sales FFF', Members: 22, Folders: 44, Quota: null, PolicySet: 'Default' },
    { ID: 50, Name: 'Sales EEE', Members: 2, Folders: 4, Quota: null, PolicySet: 'Laissez Faire' },
    { ID: 51, Name: 'Brand', Members: 120, Folders: 300, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 52, Name: 'Compliance', Members: 14, Folders: 3, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 53, Name: 'Corporate', Members: 7, Folders: 10, Quota: null, PolicySet: 'Default' },
    { ID: 54, Name: 'Education', Members: 21, Folders: 11, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 55, Name: 'Finance', Members: 12, Folders: 1, Quota: null, PolicySet: 'Default' },
    { ID: 56, Name: 'Sales QQQ', Members: 9, Folders: 0, Quota: null, PolicySet: 'Default' },
    { ID: 57, Name: 'Sales PPP', Members: 33, Folders: 14, Quota: null, PolicySet: 'Default' },
    { ID: 58, Name: 'Sales AAA', Members: 89, Folders: 6, Quota: null, PolicySet: 'Laissez Faire' },
    { ID: 59, Name: 'Sales YYY', Members: 120, Folders: 300, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 60, Name: 'Sales TTT', Members: 14, Folders: 200, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 61, Name: 'Sales GGG', Members: 7, Folders: 3, Quota: null, PolicySet: 'Default' },
    { ID: 62, Name: 'Sales BBB', Members: 21, Folders: 11, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 63, Name: 'Sales CCC', Members: 12, Folders: 4, Quota: null, PolicySet: 'Default' },
    { ID: 64, Name: 'Sales DDD', Members: 9, Folders: 5, Quota: null, PolicySet: 'Default' },
    { ID: 65, Name: 'Sales OOO', Members: 33, Folders: 6, Quota: null, PolicySet: 'Default' },
    { ID: 66, Name: 'Sales NNN', Members: 89, Folders: 12, Quota: null, PolicySet: 'Laissez Faire' },
    { ID: 67, Name: 'Sales MMM', Members: 120, Folders: 20, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 68, Name: 'Sales LLL', Members: 120, Folders: 111, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 69, Name: 'Sales KKK', Members: 7, Folders: 45, Quota: null, PolicySet: 'My Little Policy Set' },
    { ID: 70, Name: 'Sales JJJ', Members: 10, Folders: 0, Quota: null, PolicySet: 'Default' },
    { ID: 71, Name: 'Sales III', Members: 14, Folders: 4, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 72, Name: 'Sales HHH', Members: 9, Folders: 2, Quota: null, PolicySet: 'Just Another Policy Set' },
    { ID: 73, Name: 'Sales GGG', Members: 33, Folders: 1, Quota: null, PolicySet: 'Default' },
    { ID: 74, Name: 'Sales FFF', Members: 22, Folders: 44, Quota: null, PolicySet: 'Default' },
    { ID: 75, Name: 'Sales EEE', Members: 2, Folders: 4, Quota: null, PolicySet: 'Laissez Faire' },
];